osuosl/pymesync

pymesync.py, setup.py, tests.py
#17 
Since [TimeSync](https://github.com/osuosl/timesync/blob/develop/source/draft_api.rst) returns either a single JSON object or a list of several JSON objects, we should convert these objects to a list of native python objects, even if there is just one JSON object in the return. That way, a user always knows how to process the returned python list.
=> Convert JSON objects to list of python objects

pymesync.py, tests.py
* Refactor an if statement in `get_projects()`
* Return errors as python dicts instead of strings for #20
=> A little refactoring

docs/source/usage.rst, pymesync.py, tests.py
Fixed issues with double-encoding of JSON and made the date a string in tests and docs.
It actually works (minus the fact that I don't have permissions to post a time)!
```
>>> import pymesync
>>> ts = pymesync.TimeSync("http://<the-baseurl>/v1", password="not-the-real-one", user="mrsj", auth_type="password")
>>> params = {
...             "duration": 240,
...             "project": "pymesync",
...             "user": "mrsj",
...             "activities": ["code"],
...             "notes": "Worked on pymesync",
...             "issue_uri": "https://github.com/",
...             "date_worked": "2014-11-25",
...         }
>>> resp = ts.send_time(params)
>>> resp
[{u'status': 401, u'text': u'mrsj is not authorized to create time entries for project pymesync.', u'error': u'Authorization …
```
=> Fix JSON encoding issues and date -> string

docs/source/usage.rst, pymesync.py, tests.py
#70
Handle HTTP responses that do not have JSON response bodies.
* Put ``json.loads`` in a try - except block, format an error message in the except
* Rename ``_json_to_python()`` to ``_response_to_python()`` and pass it the entire response so it can handle all types
=> Handle html responses

docs/source/testing.rst, docs/source/usage.rst, pymesync.py, test_mock_pymesync.py, tests.py
See #98 for details.
Basically, this makes it so you can call `get_times` like this:
```
ts.get_times({"user": ["username1", "username2"]})
```
instead of like this:
```
ts.get_times(user=["username1", "username2"]})
```
The second option is easier to do by hand (via a CLI) but the first is easier to dynamically call because the dict can be dynamically created based on user input.
This functionality has been duplicated across ``get_projects`` and ``get_activities`` as well.
=> Refactor Queries to be Python Dicts

docs/source/developer.rst, docs/source/testing.rst, docs/source/usage.rst, pymesync/mock_pymesync.py, pymesync/pymesync.py, pymesync/test_mock_pymesync.py, pymesync/tests.py
Ref #102 
Specifically, implementing the first return option:
```
>>> ts.project_users(project="ff")
{'malcolm': ['member', 'manager'], 'jayne': ['member'], 'kaylee': ['member'], 'zoe': ['member'], 'hoban': ['member'], 'simon': ['spectator'], 'river': ['spectator'], 'derrial': ['spectator'], 'inara': ['spectator']}
```
And the functionality of the last option:
```
>>> ts.project_users(project="ff", type="manager")
['malcolm']
```
=> Create Method to Return Project Users

docs/source/testing.rst, docs/source/usage.rst, pymesync/mock_pymesync.py, pymesync/pymesync.py, pymesync/test_mock_pymesync.py, pymesync/tests.py
Ref #105 
Restructure `user` field in the project `object`.
Changes to project CRUD introduced in
API: https://github.com/osuosl/timesync/issues/59
Implementation: https://github.com/osuosl/timesync-node/issues/240
=> Update Project Crud

README.rst, docs/source/developer.rst, docs/source/usage.rst, pymesync/mock_pymesync.py, pymesync/pymesync.py, pymesync/test_mock_pymesync.py, pymesync/tests.py
Fixes #109
- `get_*` returns dict(s) within a list
- `create_*` returns a dict
- `update_*` returns a dict
- `authenticate()` returns a dict
- other simple data returns (that don't return multiple objects)
also return a dict or single element (e.g. datetime)
- error message returns are formatted identically to their parent
method
=> Refactor Return Types **BIG CHANGES**

docs/source/testing.rst, docs/source/usage.rst, pymesync/mock_pymesync.py, pymesync/pymesync.py, pymesync/test_mock_pymesync.py, pymesync/tests.py
Fixes #116 
- Fixes bug where optional user params were incorrect, causing `create_user` and `update_user` methods to fail with timesync errors.
- Fixes bug where get_* methods were returning doubly-nested lists
=> Fix optional params for users

pymesync/pymesync.py
TimeSync needs a "2a" hash prefix.
=> Change prefix to match implementation

pymesync/pymesync.py, pymesync/tests.py
Fixes #123
This allows pymesync to append the "/" itself when accessing TimeSync endpoints.
The user can choose whether or not to include the trailing "/" in the baseurl.
=> Remove trailing "/" from baseurl

docs/source/usage.rst, pymesync/pymesync.py, pymesync/tests.py
Fixes #125
Allows a time to be created without an activity when a default
activity is defined by TimeSync.
=> Make time object activities an optional field

pymesync/pymesync.py
Fixes #127 . str() fails when passed unicode.
Manual testing displayed below:
```
mrsj@pewter:~/work/pymesync/pymesync [mrsj/bugfix-unicode] (venv) » python
Python 2.7.9 (default, Mar  1 2015, 12:57:24) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pymesync
>>> ts = pymesync.TimeSync("<baseurl>")
>>> ts.authenticate("admin", "<password>", "password")
{u'token': u'YouDOnTNeEEdtoSeeAlLThis===='}
>>> ts.get_activities()
{'pymesync error': 'connection to TimeSync failed at baseurl http://timesync-staging.osuosl.org/v1 - response status was 200'}
>>> 
KeyboardInterrupt
>>> 
mrsj@pewter:~/work/pymesync/pymesync [mrsj/bugfix-unicode] (venv) » git stash apply
On branch mrsj/bugfix-unicode
Changes not staged for commit:
(use "git add …
```
=> Change str() method call to unicode()

pymesync/.github/PULL_REQUEST_TEMPLATE.md
I know, I know. I'm pushing for this everywhere. It is awesome though.
Good: Forces developers to write descriptive PRs with testing instructions. This is helpful for reviewers who aren't familiar with the code base.
Bad: Nothing.
=> Add Github PR Template

pymesync/pymesync.py, pymesync/tests.py
Bugfix. We were trying to parse the entire token, including the
randomly generated chars at the end.
Fixes #135
=> Split token on each '.' when parsing for expiration

pymesync/pymesync.py, pymesync/tests.py
Fixes issue #131
1. Run `make verify`
2. See tests and flake pass
@osuosl/devs
=> Always return a list from get_* methods

docs/source/usage.rst, pymesync/mock_pymesync.py, pymesync/test_mock_pymesync.py
fixes issue #147 
1. Run `make test`
@osuosl/devs
=> Convert "slugs" to "slug" inside mock pymesync

pymesync/tests.py
=> Fixed typo in docstring of method `test_instantiate_without_token`

docs/source/usage.rst, pymesync/mock_pymesync.py, pymesync/pymesync.py, pymesync/test_mock_pymesync.py, pymesync/tests.py
fixes issue #149 
1. Run `make test`
2. Attempt to create/update a user with a Unicode password while authenticated as a site admin
@osuosl/devs
=> Fixed Unicode support for create/update user

pymesync/mock_pymesync.py, pymesync/test_mock_pymesync.py
fixes issue #161 
1. Run `make test` inside the `pymesync/` directory
@osuosl/devs
=> Fixed update_project and get_project in mock pymesync

docs/source/usage.rst, pymesync/pymesync.py, pymesync/tests.py
fixes issue #163 
1. Run `make verify`
2. Run this script with `python`:
```
import pymesync
ts = pymesync.TimeSync(baseurl='http://timesync-staging.osuosl.org/v0')
ts.authenticate('admin', 'timesync-staging', 'password')
ts.get_projects({"user": ["mrsj"]})
```
See that all of the projects that were returned contain the user "mrsj"
@osuosl/devs
=> Added "user" query parameter to get_projects

pymesync/pymesync.py
fixes issue #169 
1.Run this script
```python
import pymesync
ts = pymesync.TimeSync(baseurl="http://timesync-staging.osuosl.org/v0")
ts.authenticate("test", "test", "password")
ts.project_users(project="tp")
```
2.See that it doesn't raise a KeyError and that `ts.project_users(project="tp")` just returns an empty dict
@osuosl/devs
=> Fixed KeyError in project_users()

docs/source/usage.rst, pymesync/pymesync.py, tests/test_pymesync.py
fixes issue #167 
1. Run `make verify`
2. Run this script or type these into the python shell
```
import pymesync
ts = pymesync.TimeSync(baseurl="http://timesync-staging.osuosl.org/v0")
ts.authenticate("test", "test", "password")
print ts.get_times(query_parameters={"start": "2016-01-01", "end": "2016-06-01"})
```
@osuosl/devs
=> Allow "start" and "end" query parameters to be submitted as strings

.travis.yml, requirements.txt, setup.py
Fixes an issue in Debian 10 / python 2.7 where bcrypt wasn't able to find gnu-crypt.h
=> update bcrypt version to work with newer versions of python
