osuosl/pymesync

.travis.yml, pymesync.py, tests.py
=> GET times method

.travis.yml, pymesync.py, tests.py
=> GET projects, projects/<slug>, projects?query_params

pymesync.py, tests.py
Fixes #16 
Documentation will be added in #22 since there is no documentation here yet.
=> Make API version the user's responsibility

.travis.yml, Makefile, README.md, docs/source/usage.rst, pymesync.py, tests.py
=> GET time by id

docs/source/usage.rst, pymesync.py, tests.py
=> GET activities

pymesync.py
=> Move endpoint formatting to internal function

pymesync.py, tests.py
=> Parameter Checking

pymesync.py, tests.py
=> Test for send_times with uuid

docs/source/usage.rst, pymesync.py, tests.py
=> Refactor and Rename create/update methods

pymesync.py, tests.py
Updates pymesync to current implementation of TimeSync. See https://github.com/osuosl/timesync/issues/49 and https://github.com/osuosl/timesync-node/issues/218 for more information.
Fixes #52
=> Fix Parameter Checking

docs/source/usage.rst
=> Refactor Documentation

pymesync.py, tests.py
=> Token Auth

docs/source/usage.rst, pymesync.py, tests.py
=> Change revisions -> include_revisions to reflect API change

docs/source/usage.rst, pymesync.py, tests.py
=> GET times/uuid?include_*

pymesync.py, tests.py
=> Create and update user

docs/source/usage.rst
=> Add user CRUD usage docs

tests.py
* Replace hard-coded error message with object variable
* Add additional types to ``param_list``
=> Minor refactor of tests

pymesync.py, requirements.txt, tests.py
=> Bugfix authentication on DELETE

Makefile, docs/source/index.rst, docs/source/testing.rst, mock_pymesync.py, pymesync.py, test_mock_pymesync.py
Creates a test mode so users can run tests on their code that uses pymesync without having to mock pymesync or execute expensive API calls.
=> Pymesync Test Mode

pymesync.py, tests.py
Make internal methods private according to https://docs.python.org/2/tutorial/classes.html#tut-private
=> Make internal methods private

docs/source/usage.rst, pymesync.py, tests.py
=> Instantiate with Token

docs/source/developer.rst, docs/source/index.rst
=> Add developer docs

docs/source/usage.rst
Add usage examples to the usage document.
Fixes #38
=> Usage Examples

Makefile, docs/source/testing.rst, pymesync.py, tests.py
=> Return status code on successful delete

docs/source/developer.rst, docs/source/testing.rst, docs/source/usage.rst, mock_pymesync.py, pymesync.py, test_mock_pymesync.py, tests.py
=> Method to Return Token Expiration

pymesync.py
Add verbose comments to make it easier for other developers to contribute.
=> Add More Comments

docs/source/usage.rst, pymesync/pymesync.py, pymesync/tests.py
=> Update User Crud

pymesync/pymesync.py, pymesync/tests.py
=> Append token to GET users

pymesync/pymesync.py, pymesync/tests.py, setup.py
- Fixes bug where the token was not appended to GET requests on the `/users` endpoint.
=> Append token to get users requests

pymesync/pymesync.py, pymesync/tests.py, requirements.txt, setup.py
=> Encrypt user object passwords

pymesync/Makefile
This just fixes a typo and removes some code repetition.
=> Fix Makefile typo, slight edits

docs/source/usage.rst
Fixes #131
It is now clear that the get_* methods return a list containing
zero or more python dicts.
=> Clarify docs for get_* methods

pymesync/tests.py
=> removed method test_duration_invalid from tests

pymesync/tests.py
`Ran 138 tests in 1.599s`
`Ran 138 tests in 0.600s`
@osuosl/devs
=> Removed unused patch decorators

pymesync/tests.py
=> Removed tests that use network connection.

docs/source/developer.rst
fixes #144 
```
(venv) $ cd docs
(venv) $ make html
(venv) $ <your-favorite-web-browser> build/html/index.html
```
You can review the content directly on the web page that is opened.
@osuosl/devs
=> Documentation for PyPi uploads

docs/source/testing.rst, pymesync/mock_pymesync.py, pymesync/test_mock_pymesync.py
Fixes #142 
1. Run `make verify`
2. See tests and flake pass
3. Read the additions to docs/source/testing.rst
@osuosl/devs
=> Mock permissions depending on username

docs/source/testing.rst, pymesync/mock_pymesync.py, pymesync/test_mock_pymesync.py
Merge develop into master for next point release.
@osuosl/devs
=> merge with master
